Update actions.ts
svramu/iBot pull request #2
Opened 2022-10-07 10:23 UTC by senthilsb-toast

added clear input and uncommented dnd it is working

2022-10-07 14:04 UTC, svramu commented on actions.ts
> +          case "key:clear":
Since we can do this with 'keys' action and empty data, this can be removed.

2022-10-10 01:19 UTC, svramu requested changes
trying this process

2022-10-10 01:19 UTC, svramu commented on actions.ts
> +          case "key:clear":
Since we can do this with 'keys' action and empty data, this can be removed.

2022-12-08 07:06 UTC, closed without merging

2022-12-08 07:06 UTC, senthilsb-toast commented
Not Required